// <auto-generated />
using Homework3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Homework3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604120122_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Homework3.Models.Database", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeGb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Databases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CRM_Prod",
                            ServerId = 1,
                            SizeGb = 512
                        },
                        new
                        {
                            Id = 2,
                            Name = "ERP_Finance",
                            ServerId = 1,
                            SizeGb = 1024
                        },
                        new
                        {
                            Id = 3,
                            Name = "Analytics_Dev",
                            ServerId = 2,
                            SizeGb = 256
                        },
                        new
                        {
                            Id = 4,
                            Name = "Reporting",
                            ServerId = 2,
                            SizeGb = 128
                        },
                        new
                        {
                            Id = 5,
                            Name = "MainDB",
                            ServerId = 3,
                            SizeGb = 64
                        },
                        new
                        {
                            Id = 6,
                            Name = "BackupDB",
                            ServerId = 3,
                            SizeGb = 32
                        },
                        new
                        {
                            Id = 7,
                            Name = "UserData",
                            ServerId = 4,
                            SizeGb = 512
                        },
                        new
                        {
                            Id = 8,
                            Name = "Logs",
                            ServerId = 4,
                            SizeGb = 256
                        },
                        new
                        {
                            Id = 9,
                            Name = "Warehouse",
                            ServerId = 5,
                            SizeGb = 2048
                        },
                        new
                        {
                            Id = 10,
                            Name = "Staging",
                            ServerId = 5,
                            SizeGb = 1024
                        },
                        new
                        {
                            Id = 11,
                            Name = "TestEnv",
                            ServerId = 1,
                            SizeGb = 128
                        },
                        new
                        {
                            Id = 12,
                            Name = "Archive",
                            ServerId = 3,
                            SizeGb = 16
                        },
                        new
                        {
                            Id = 13,
                            Name = "TempDB",
                            ServerId = 2,
                            SizeGb = 64
                        },
                        new
                        {
                            Id = 14,
                            Name = "ConfigDB",
                            ServerId = 4,
                            SizeGb = 32
                        },
                        new
                        {
                            Id = 15,
                            Name = "Metabase",
                            ServerId = 5,
                            SizeGb = 512
                        });
                });

            modelBuilder.Entity("Homework3.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oracle Enterprise"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Microsoft SQL Server"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 4,
                            Name = "MongoDB Atlas"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IBM Db2"
                        });
                });

            modelBuilder.Entity("Homework3.Models.Database", b =>
                {
                    b.HasOne("Homework3.Models.Server", "Server")
                        .WithMany("Databases")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Homework3.Models.Server", b =>
                {
                    b.Navigation("Databases");
                });
#pragma warning restore 612, 618
        }
    }
}
